# src/modules/geometry/ellipsoid.py
"""
Generates ellipsoids by applying different deformations and rotations.

This module provides functions to create ellipsoids by generating semicircles,
mirroring them to form full circles, applying horizontal deformations, and rotating
the shapes. The generated ellipsoids are saved as STL and PNG files.

Functions:
- create_ellipsoid(left_factor, right_factor, rotation_angle): Generates an ellipsoid
  by deforming and rotating a circle.
- generate_ellipsoids(): Generates and saves all possible ellipsoids with deformation
  and rotation combinations.

The module ensures that the necessary directories for saving images and STL files exist.
"""

import numpy as np
import shapely.geometry as sg

from modules.geometry.semicircles import create_semicircle
from modules.geometry.transform_utils import (
    stretch_both_sides,
    rotate_shape,
    merge_shapes,
)
from modules.geometry.shape_utils import save_as_stl, save_as_png

# Deformation factors for left and right halves
DEFORMATION_FACTORS = [0.75, 1.0, 1.5, 2.0]
# Rotation angles in degrees (excluding mirrored redundancies)
ROTATION_ANGLES = [0, 15, 30, 45, 60, 75]


def create_ellipsoid(left_factor, right_factor, rotation_angle):
    """
    Generate an ellipsoid by deforming and rotating a circle.

    This function creates an ellipsoid by first generating a semicircle, mirroring it
    to form a full circle, applying horizontal deformations to both sides, and finally
    rotating the shape by a specified angle.

    Parameters:
        left_factor (float): Stretch/compression factor for the left side.
        right_factor (float): Stretch/compression factor for the right side.
        rotation_angle (float): Rotation angle in degrees.

    Returns:
        tuple: (vertices, faces) - Computed points and faces for the ellipsoid.
    """
    # Generate a semicircle to start the ellipsoid shape
    vertices1, faces1 = create_semicircle()

    # Mirror the semicircle to create a full circle shape
    vertices, faces = merge_shapes(vertices1, faces1)

    # Apply horizontal deformation factors to the left and right halves
    left_factor, right_factor = sorted([left_factor, right_factor])
    vertices = stretch_both_sides(vertices, left_factor, right_factor)

    # Rotate the deformed shape only if it is not a perfect circle
    if (left_factor, right_factor) != (1.0, 1.0):
        vertices = rotate_shape(vertices, rotation_angle)

    # Return the final vertices and faces of the ellipsoid
    return vertices, faces


def generate_ellipsoids():
    """
    Generate and save all possible ellipsoids with deformation and rotation combinations.

    The function iterates over predefined deformation factors and rotation angles to create unique
    ellipsoid shapes. Each shape is saved as both an STL and PNG file.

    Notes:
        - The original (non-deformed) circle is added if it is not already generated by the
          transformation combinations.
    """
    # Precompute filename and transformation parameters
    transformations = [
        (left_factor, right_factor, rotation_angle)
        for left_factor in DEFORMATION_FACTORS
        for right_factor in DEFORMATION_FACTORS
        if (left_factor, right_factor) != (1.0, 1.0)
        for rotation_angle in ROTATION_ANGLES
    ]

    # Iterate through each transformation to generate and save ellipsoids
    for left_factor, right_factor, rotation_angle in transformations:
        # Construct the filename based on transformation parameters
        filename = (
            f"ellipsoid_Ldef{int(left_factor * 100):03d}_"
            f"Rdef{int(right_factor * 100):03d}_"
            f"Rot{int(rotation_angle):03d}"
        )
        # Generate the ellipsoid geometry
        vertices, faces = create_ellipsoid(left_factor, right_factor, rotation_angle)
        # Save the ellipsoid as an STL file
        save_as_stl(vertices, faces, filename)
        # Save the ellipsoid as a PNG image
        save_as_png(vertices, filename)

    # Check if the original (non-deformed) circle is not included, and add it if necessary
    if (1.0, 1.0) not in [(left, right) for left, right, _ in transformations]:
        # Filename for the original circle
        filename = "ellipsoid_Ldef100_Rdef100_Rot000"
        # Generate the original circle
        vertices, faces = create_ellipsoid(1.0, 1.0, 0)
        # Save the original circle as an STL file
        save_as_stl(vertices, faces, filename)
        # Save the original circle as a PNG image
        save_as_png(vertices, filename)


# ---------------------------------------------------------------------------- #
# Função para gerar um semicírculo
import numpy as np
import shapely.geometry as sg


def create_semicircle(center=(0, 0), radius=1, num_points=50):
    """
    Gera um semicírculo com base no eixo X e com centro especificado.
    O semicírculo terá a base no eixo X e será voltado para cima.
    """
    # Gerar os pontos da curva do semicírculo (usando um arco do círculo)
    points = [
        (center[0] + radius * np.cos(theta), center[1] + radius * np.sin(theta))
        for theta in np.linspace(np.pi / 2, -np.pi / 2, num_points)
    ]

    # Adicionar os pontos da base (linha reta)
    points_base = [(x, center[1]) for x, y in points]

    # Criar o polígono do semicírculo
    semi_circle = sg.Polygon(points_base + points)

    return semi_circle


# ---------------------------------------------------------------------------- #


# Execute directly if needed
if __name__ == "__main__":
    generate_ellipsoids()
